/* 
 * OriginStamp Client
 * 
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using OriginStamp.Client.Client;
using OriginStamp.Client.Model;

namespace OriginStamp.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISchedulerApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// NextSchedule
        /// </summary>
        /// <remarks>
        /// Get the next scheduling time for hash submissions to the blockchain.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>DefaultSchedulerResponse</returns>
        DefaultSchedulerResponse GetNextSchedulingTime (string authorization, SchedulerRequest schedulerRequest);

        /// <summary>
        /// NextSchedule
        /// </summary>
        /// <remarks>
        /// Get the next scheduling time for hash submissions to the blockchain.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>ApiResponse of DefaultSchedulerResponse</returns>
        ApiResponse<DefaultSchedulerResponse> GetNextSchedulingTimeWithHttpInfo (string authorization, SchedulerRequest schedulerRequest);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// NextSchedule
        /// </summary>
        /// <remarks>
        /// Get the next scheduling time for hash submissions to the blockchain.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>Task of DefaultSchedulerResponse</returns>
        System.Threading.Tasks.Task<DefaultSchedulerResponse> GetNextSchedulingTimeAsync (string authorization, SchedulerRequest schedulerRequest);

        /// <summary>
        /// NextSchedule
        /// </summary>
        /// <remarks>
        /// Get the next scheduling time for hash submissions to the blockchain.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>Task of ApiResponse (DefaultSchedulerResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DefaultSchedulerResponse>> GetNextSchedulingTimeAsyncWithHttpInfo (string authorization, SchedulerRequest schedulerRequest);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SchedulerApi : ISchedulerApi
    {
        private OriginStamp.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SchedulerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SchedulerApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = OriginStamp.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SchedulerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SchedulerApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = OriginStamp.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OriginStamp.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// NextSchedule Get the next scheduling time for hash submissions to the blockchain.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>DefaultSchedulerResponse</returns>
        public DefaultSchedulerResponse GetNextSchedulingTime (string authorization, SchedulerRequest schedulerRequest)
        {
             ApiResponse<DefaultSchedulerResponse> localVarResponse = GetNextSchedulingTimeWithHttpInfo(authorization, schedulerRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// NextSchedule Get the next scheduling time for hash submissions to the blockchain.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>ApiResponse of DefaultSchedulerResponse</returns>
        public ApiResponse< DefaultSchedulerResponse > GetNextSchedulingTimeWithHttpInfo (string authorization, SchedulerRequest schedulerRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling SchedulerApi->GetNextSchedulingTime");
            // verify the required parameter 'schedulerRequest' is set
            if (schedulerRequest == null)
                throw new ApiException(400, "Missing required parameter 'schedulerRequest' when calling SchedulerApi->GetNextSchedulingTime");

            var localVarPath = "/v3/submission/times";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (schedulerRequest != null && schedulerRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(schedulerRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = schedulerRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetNextSchedulingTime", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultSchedulerResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultSchedulerResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultSchedulerResponse)));
        }

        /// <summary>
        /// NextSchedule Get the next scheduling time for hash submissions to the blockchain.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>Task of DefaultSchedulerResponse</returns>
        public async System.Threading.Tasks.Task<DefaultSchedulerResponse> GetNextSchedulingTimeAsync (string authorization, SchedulerRequest schedulerRequest)
        {
             ApiResponse<DefaultSchedulerResponse> localVarResponse = await GetNextSchedulingTimeAsyncWithHttpInfo(authorization, schedulerRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// NextSchedule Get the next scheduling time for hash submissions to the blockchain.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="schedulerRequest">Request DTO for next schedules.</param>
        /// <returns>Task of ApiResponse (DefaultSchedulerResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DefaultSchedulerResponse>> GetNextSchedulingTimeAsyncWithHttpInfo (string authorization, SchedulerRequest schedulerRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling SchedulerApi->GetNextSchedulingTime");
            // verify the required parameter 'schedulerRequest' is set
            if (schedulerRequest == null)
                throw new ApiException(400, "Missing required parameter 'schedulerRequest' when calling SchedulerApi->GetNextSchedulingTime");

            var localVarPath = "/v3/submission/times";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (schedulerRequest != null && schedulerRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(schedulerRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = schedulerRequest; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetNextSchedulingTime", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultSchedulerResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultSchedulerResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultSchedulerResponse)));
        }

    }
}
