/*
 * OriginStamp Client
 *
 * OpenAPI spec version: 3.0
 * OriginStamp Documentation: https://docs.originstamp.com
 * Contact: mail@originstamp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using OriginStamp.Client.Client;
using OriginStamp.Client.Model;

namespace OriginStamp.Client.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWebhookApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>DefaultOfWebhookResponse</returns>
        DefaultOfWebhookResponse GetWebhookStatus (string authorization, WebhookRequest webhookRequest);

        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>ApiResponse of DefaultOfWebhookResponse</returns>
        ApiResponse<DefaultOfWebhookResponse> GetWebhookStatusWithHttpInfo (string authorization, WebhookRequest webhookRequest);
        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>DefaultOfVoid</returns>
        DefaultOfVoid RegisterWebhookNotification (string authorization, WebhookRequest webhookRequest);

        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>ApiResponse of DefaultOfVoid</returns>
        ApiResponse<DefaultOfVoid> RegisterWebhookNotificationWithHttpInfo (string authorization, WebhookRequest webhookRequest);
        /// <summary>
        /// Dev
        /// </summary>
        /// <remarks>
        /// With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>DefaultOfstring</returns>
        DefaultOfstring TriggerTimestampWebhook (string authorization, ManualWebhookRequest manualWebhookRequest);

        /// <summary>
        /// Dev
        /// </summary>
        /// <remarks>
        /// With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>ApiResponse of DefaultOfstring</returns>
        ApiResponse<DefaultOfstring> TriggerTimestampWebhookWithHttpInfo (string authorization, ManualWebhookRequest manualWebhookRequest);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>Task of DefaultOfWebhookResponse</returns>
        System.Threading.Tasks.Task<DefaultOfWebhookResponse> GetWebhookStatusAsync (string authorization, WebhookRequest webhookRequest);

        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>Task of ApiResponse (DefaultOfWebhookResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DefaultOfWebhookResponse>> GetWebhookStatusAsyncWithHttpInfo (string authorization, WebhookRequest webhookRequest);
        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>Task of DefaultOfVoid</returns>
        System.Threading.Tasks.Task<DefaultOfVoid> RegisterWebhookNotificationAsync (string authorization, WebhookRequest webhookRequest);

        /// <summary>
        /// Webhook
        /// </summary>
        /// <remarks>
        /// Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>Task of ApiResponse (DefaultOfVoid)</returns>
        System.Threading.Tasks.Task<ApiResponse<DefaultOfVoid>> RegisterWebhookNotificationAsyncWithHttpInfo (string authorization, WebhookRequest webhookRequest);
        /// <summary>
        /// Dev
        /// </summary>
        /// <remarks>
        /// With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>Task of DefaultOfstring</returns>
        System.Threading.Tasks.Task<DefaultOfstring> TriggerTimestampWebhookAsync (string authorization, ManualWebhookRequest manualWebhookRequest);

        /// <summary>
        /// Dev
        /// </summary>
        /// <remarks>
        /// With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </remarks>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>Task of ApiResponse (DefaultOfstring)</returns>
        System.Threading.Tasks.Task<ApiResponse<DefaultOfstring>> TriggerTimestampWebhookAsyncWithHttpInfo (string authorization, ManualWebhookRequest manualWebhookRequest);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WebhookApi : IWebhookApi
    {
        private OriginStamp.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WebhookApi(String basePath)
        {
            this.Configuration = new OriginStamp.Client.Client.Configuration { BasePath = basePath };

            ExceptionFactory = OriginStamp.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WebhookApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WebhookApi(OriginStamp.Client.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = OriginStamp.Client.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = OriginStamp.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public OriginStamp.Client.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public OriginStamp.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Webhook RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>DefaultOfWebhookResponse</returns>
        public DefaultOfWebhookResponse GetWebhookStatus (string authorization, WebhookRequest webhookRequest)
        {
             ApiResponse<DefaultOfWebhookResponse> localVarResponse = GetWebhookStatusWithHttpInfo(authorization, webhookRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Webhook RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>ApiResponse of DefaultOfWebhookResponse</returns>
        public ApiResponse< DefaultOfWebhookResponse > GetWebhookStatusWithHttpInfo (string authorization, WebhookRequest webhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->GetWebhookStatus");
            // verify the required parameter 'webhookRequest' is set
            if (webhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'webhookRequest' when calling WebhookApi->GetWebhookStatus");

            var localVarPath = "/v3/webhook/information";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (webhookRequest != null && webhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(webhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = webhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWebhookStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfWebhookResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfWebhookResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfWebhookResponse)));
        }

        /// <summary>
        /// Webhook RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>Task of DefaultOfWebhookResponse</returns>
        public async System.Threading.Tasks.Task<DefaultOfWebhookResponse> GetWebhookStatusAsync (string authorization, WebhookRequest webhookRequest)
        {
             ApiResponse<DefaultOfWebhookResponse> localVarResponse = await GetWebhookStatusAsyncWithHttpInfo(authorization, webhookRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Webhook RESTful interface to receive the status of a webhook. Based on the input parameters (target URL, hash and currency), we look up the most recent entry in the notification queue.This method is intended to support the webhook integration.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for registering webhook information.</param>
        /// <returns>Task of ApiResponse (DefaultOfWebhookResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DefaultOfWebhookResponse>> GetWebhookStatusAsyncWithHttpInfo (string authorization, WebhookRequest webhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->GetWebhookStatus");
            // verify the required parameter 'webhookRequest' is set
            if (webhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'webhookRequest' when calling WebhookApi->GetWebhookStatus");

            var localVarPath = "/v3/webhook/information";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (webhookRequest != null && webhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(webhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = webhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetWebhookStatus", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfWebhookResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfWebhookResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfWebhookResponse)));
        }

        /// <summary>
        /// Webhook Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>DefaultOfVoid</returns>
        public DefaultOfVoid RegisterWebhookNotification (string authorization, WebhookRequest webhookRequest)
        {
             ApiResponse<DefaultOfVoid> localVarResponse = RegisterWebhookNotificationWithHttpInfo(authorization, webhookRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Webhook Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>ApiResponse of DefaultOfVoid</returns>
        public ApiResponse< DefaultOfVoid > RegisterWebhookNotificationWithHttpInfo (string authorization, WebhookRequest webhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->RegisterWebhookNotification");
            // verify the required parameter 'webhookRequest' is set
            if (webhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'webhookRequest' when calling WebhookApi->RegisterWebhookNotification");

            var localVarPath = "/v3/webhook/register";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (webhookRequest != null && webhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(webhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = webhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegisterWebhookNotification", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfVoid>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfVoid) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfVoid)));
        }

        /// <summary>
        /// Webhook Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>Task of DefaultOfVoid</returns>
        public async System.Threading.Tasks.Task<DefaultOfVoid> RegisterWebhookNotificationAsync (string authorization, WebhookRequest webhookRequest)
        {
             ApiResponse<DefaultOfVoid> localVarResponse = await RegisterWebhookNotificationAsyncWithHttpInfo(authorization, webhookRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Webhook Method which allows a subscription for a webhook notification. If this method is called, a new entry is added to notification queue that is triggered as soon as a tamper-proof timestamp or the hash is created. An empty data payload means that the entry was created successfully.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="webhookRequest">DTO for querying webhook information.</param>
        /// <returns>Task of ApiResponse (DefaultOfVoid)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DefaultOfVoid>> RegisterWebhookNotificationAsyncWithHttpInfo (string authorization, WebhookRequest webhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->RegisterWebhookNotification");
            // verify the required parameter 'webhookRequest' is set
            if (webhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'webhookRequest' when calling WebhookApi->RegisterWebhookNotification");

            var localVarPath = "/v3/webhook/register";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (webhookRequest != null && webhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(webhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = webhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RegisterWebhookNotification", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfVoid>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfVoid) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfVoid)));
        }

        /// <summary>
        /// Dev With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>DefaultOfstring</returns>
        public DefaultOfstring TriggerTimestampWebhook (string authorization, ManualWebhookRequest manualWebhookRequest)
        {
             ApiResponse<DefaultOfstring> localVarResponse = TriggerTimestampWebhookWithHttpInfo(authorization, manualWebhookRequest);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Dev With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>ApiResponse of DefaultOfstring</returns>
        public ApiResponse< DefaultOfstring > TriggerTimestampWebhookWithHttpInfo (string authorization, ManualWebhookRequest manualWebhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->TriggerTimestampWebhook");
            // verify the required parameter 'manualWebhookRequest' is set
            if (manualWebhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'manualWebhookRequest' when calling WebhookApi->TriggerTimestampWebhook");

            var localVarPath = "/v3/webhook/start";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (manualWebhookRequest != null && manualWebhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(manualWebhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = manualWebhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TriggerTimestampWebhook", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfstring>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfstring) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfstring)));
        }

        /// <summary>
        /// Dev With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>Task of DefaultOfstring</returns>
        public async System.Threading.Tasks.Task<DefaultOfstring> TriggerTimestampWebhookAsync (string authorization, ManualWebhookRequest manualWebhookRequest)
        {
             ApiResponse<DefaultOfstring> localVarResponse = await TriggerTimestampWebhookAsyncWithHttpInfo(authorization, manualWebhookRequest);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Dev With this interface you can trigger manual webhook to see how a webhook looks like. Please use a hash, that was already timestamped before such as https://redir.originstamp.com/hash/9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08 . Usually, the webhook is triggered as soon as the tamper-proof time stamp with the selected crypto currency has been created.
        /// </summary>
        /// <exception cref="OriginStamp.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorization">A valid API key is essential for authorization to handle the request.</param>
        /// <param name="manualWebhookRequest">DTO for webhook request.</param>
        /// <returns>Task of ApiResponse (DefaultOfstring)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DefaultOfstring>> TriggerTimestampWebhookAsyncWithHttpInfo (string authorization, ManualWebhookRequest manualWebhookRequest)
        {
            // verify the required parameter 'authorization' is set
            if (authorization == null)
                throw new ApiException(400, "Missing required parameter 'authorization' when calling WebhookApi->TriggerTimestampWebhook");
            // verify the required parameter 'manualWebhookRequest' is set
            if (manualWebhookRequest == null)
                throw new ApiException(400, "Missing required parameter 'manualWebhookRequest' when calling WebhookApi->TriggerTimestampWebhook");

            var localVarPath = "/v3/webhook/start";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorization != null) localVarHeaderParams.Add("Authorization", this.Configuration.ApiClient.ParameterToString(authorization)); // header parameter
            if (manualWebhookRequest != null && manualWebhookRequest.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(manualWebhookRequest); // http body (model) parameter
            }
            else
            {
                localVarPostBody = manualWebhookRequest; // byte array
            }

            // authentication (API Key Authorization) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarHeaderParams["Authorization"] = this.Configuration.GetApiKeyWithPrefix("Authorization");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("TriggerTimestampWebhook", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DefaultOfstring>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DefaultOfstring) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(DefaultOfstring)));
        }

    }
}
